---
hero_image: images/team-chooser.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Team Chooser
description: Make a program to split players into 2 random teams.
original_url: https://codeclubprojects.org/en-GB/python/editor-team-chooser
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2018-04-05
steps:
- title: What you will make
- title: Create a player list
- title: Add more players
  completion:
  - engaged
- title: Choose a random player
- title: Create two teams
- title: Split everyone into teams
- title: Load players from a file
- title: Handle an odd player
  completion:
  - internal
- title: Add random team names
- title: Load team names from a file
- title: Challenges
  completion:
  - external
  challenge: true
